export const siteConfig = {
  name: "KotoGelo",
  banglaName: "কত গেলো?",
  tagline: "Smart Expense Manager & Group Bill Splitter",
  banglaTagline: "দৈনিক খরচের হিসাব ও মেস ম্যানেজমেন্টের সহজ সমাধান",
  description:
    "হিসাব রাখা এখন জলের মতো সহজ! Track personal expenses, manage mess and tour bills, visualize monthly spending, and settle debts instantly with KotoGelo.",
  fullDescription:
    "KotoGelo (কত গেলো?) is the smartest, fastest, and most intuitive personal expense tracker and group bill manager in Bangladesh. Easily track daily expenses, manage student mess bachelor meals, tour split costs, analyze spending categories with rich analytics, and settle debts with 100% privacy and offline-first support.",
  url: "https://kotogelo.app",
  ogImage: "https://kotogelo.app/logo.png",
  logo: "/logo.png",
  favicon: "/favicon.svg",
  themeColor: "#2563EB",
  backgroundColor: "#020617",
  creator: "KotoGelo Team",
  authors: [
    {
      name: "KotoGelo Team",
      url: "https://kotogelo.app",
    },
  ],
  keywords: [
    "KotoGelo",
    "কত গেলো",
    "Expense Tracker BD",
    "Expense Tracker Bangladesh",
    "Mess Manager BD",
    "মেস ম্যানেজার",
    "Split Bill Bangladesh",
    "Daily Expense App",
    "Personal Finance App",
    "Money Manager",
    "Bachelor Mess Manager",
    "Tour Expense Splitter",
    "Taka Hishab",
    "টাকার হিসাব",
    "Daily Budget Planner",
    "Offline Expense Tracker",
    "bKash Nagad Expense Management",
  ],
  links: {
    github: "https://github.com/your-username/kotogelo",
    playstore: "https://play.google.com/store/apps/details?id=com.kotogelo.app",
    appstore: "https://apps.apple.com/app/kotogelo/id123456789",
    apkDirect: "https://github.com/your-username/kotogelo/releases/latest/download/kotogelo.apk",
    twitter: "https://twitter.com/kotogelo",
  },
  navItems: [
    { label: "Features", href: "#features" },
    { label: "How It Works", href: "#how-it-works" },
    { label: "Advantages", href: "#advantages" },
    { label: "Tech Stack", href: "#technologies" },
    { label: "Download", href: "#download" },
  ],
  stats: [
    { value: "৳০", label: "Hidden Fees / 100% Free" },
    { value: "100%", label: "Offline First Security" },
    { value: "< 1 Sec", label: "Instant Quick Entry" },
    { value: "4.9 ★", label: "User Rating" },
  ],
};
